# Generated by Django 5.0.4 on 2024-06-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0003_alter_produccion_cantidad_leche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='cantidad_leche',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='cantidad_vendidas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
